development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: wbam_dev
  pool: 5
  username: wbam
  password: wbam
  #**socket: /opt/local/var/run/mysql5/mysqld.sock**

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: wbam_test
  pool: 5
  username: wbam
  password: wbam
  #**socket: /opt/local/var/run/mysql5/mysqld.sock**

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: wbam_prod
  pool: 5
  username: wbam
  password: wbam
  #**socket: /opt/local/var/run/mysql5/mysqld.sock**